sonar.projectKey=chauhan-mukesh_pimcore-market-readiness-shield
sonar.organization=chauhan-mukesh
sonar.projectName=Market Readiness Shield
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src/Tests
sonar.exclusions=src/Tests/**,src/Migrations/**,src/Resources/public/studio/node_modules/**

# PHP coverage
sonar.php.coverage.reportPaths=coverage/clover.xml

# TypeScript / JS
sonar.javascript.lcov.reportPaths=src/Resources/public/studio/coverage/lcov.info

sonar.sourceEncoding=UTF-8
